export const PRODUCT_LIST_PENDING = 'PRODUCT_LIST_PENDING';
export const PRODUCT_LIST_FULFILLED = 'PRODUCT_LIST_FULFILLED';
export const PRODUCT_LIST_REJECTED = 'PRODUCT_LIST_REJECTED';
export const PRODUCT_LIST_SEARCH_PENDING = 'PRODUCT_LIST_SEARCH_PENDING';
export const PRODUCT_LIST_SEARCH_FULFILLED = 'PRODUCT_LIST_SEARCH_FULFILLED';
export const PRODUCT_LIST_SEARCH_REJECTED = 'PRODUCT_LIST_SEARCH_REJECTED';